[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/sensokame/esp-ota-simplified.git#v1.1.0
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.9
    mathieucarbou/ESP Async WebServer@^3.0.0
    mathieucarbou/AsyncTCP@^3.0.0
    bblanchon/ArduinoJson@^6.21.3
    adafruit/Adafruit GFX Library@^1.11.0
board_build.partitions = partitions.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
