[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.9
    ESP Async WebServer@^1.2.4
    ESP AsyncTCP@^1.2.2
    bblanchon/ArduinoJson@^6.21.3
build_flags =
    -DCORE_DEBUG_LEVEL=1
